name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment to deploy (dev or prod)'
        required: true
        default: 'dev'
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Environment Variables
      run: |
        if [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
          echo "Setting variables for dev"
          echo "DB_URL=${{ secrets.DEV_DB_URL }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.DEV_API_KEY }}" >> $GITHUB_ENV
        elif [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
          echo "Setting variables for prod"
          echo "DB_URL=${{ secrets.PROD_DB_URL }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.PROD_API_KEY }}" >> $GITHUB_ENV
        fi

    - name: Verify Environment Variables
      run: |
        echo "Deploying to environment: ${{ github.event.inputs.environment }}"
        echo "DB_URL is $DB_URL"
        echo "API_KEY is $API_KEY"
